services:
  camodocal:
    container_name: camodocal-dev
    build:
      dockerfile: Dockerfile
    network_mode: "host"
    runtime: nvidia
    privileged: true
    ipc: host
    volumes:
      - .:/root/data_host
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
    environment:
      - "DISPLAY=${DISPLAY}"
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command:  
      - /bin/bash
    tty: true
    stdin_open: true
    security_opt:
        - seccomp:unconfined
        - apparmor:unconfined
    cap_add:
        - CAP_SYS_PTRACE
